name: Vprofile actions

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks
  IMAGE_URI: 513237888288.dkr.ecr.us-east-1.amazonaws.com/vprofile

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Resolve dependencies
        run: mvn dependency:resolve

      - name: Build + Test + Checkstyle
        run: mvn -U clean package    


      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/ \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.qualitygate.wait=false   # optional but recommended

      
          
  docker:
      runs-on: ubuntu-latest
      needs: Testing  # 🔥 runs only if build job succeeds

      steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Login to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build Docker Image
          run: docker build -t vprofile .

        - name: Tag Docker Image
          run: |
            docker tag vprofile:latest ${{ env.IMAGE_URI }}:latest

        - name: Push to ECR
          run: |
            docker push ${{ env.IMAGE_URI }}:latest         
            
            
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Install kubectl
          uses: azure/setup-kubectl@v4

        - name: Install Helm
          uses: azure/setup-helm@v4

        - name: Connect to EKS
          run: |
            aws eks update-kubeconfig --region us-east-1 --name vprofile-eks

        - name: Verify connection
          run: kubectl get nodes

        - name: Deploy using Helm
          run: |
            helm upgrade --install vprofile-release ./helm/vprofilecharts \
              --set image.repository=513237888288.dkr.ecr.us-east-1.amazonaws.com/vprofile \
              --set image.tag=latest
              